# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_are_possible_ancestors <- function(t_inf, alpha, genotype, cluster, i) {
    .Call(`_measlesoutbreaker_cpp_are_possible_ancestors`, t_inf, alpha, genotype, cluster, i)
}

cpp_log_like <- function(population, distance, a, b, gamma, spatial, nb_cases) {
    .Call(`_measlesoutbreaker_cpp_log_like`, population, distance, a, b, gamma, spatial, nb_cases)
}

cpp_find_descendents <- function(alpha, cluster, i) {
    .Call(`_measlesoutbreaker_cpp_find_descendents`, alpha, cluster, i)
}

cpp_find_all_descendents <- function(alpha, t_inf, cluster, i) {
    .Call(`_measlesoutbreaker_cpp_find_all_descendents`, alpha, t_inf, cluster, i)
}

cpp_find_all_tree <- function(alpha, t_inf, cluster, i) {
    .Call(`_measlesoutbreaker_cpp_find_all_tree`, alpha, t_inf, cluster, i)
}

cpp_find_local_cases <- function(alpha, cluster, i) {
    .Call(`_measlesoutbreaker_cpp_find_local_cases`, alpha, cluster, i)
}

cpp_swap_cases <- function(param, cluster, i) {
    .Call(`_measlesoutbreaker_cpp_swap_cases`, param, cluster, i)
}

cpp_ll_timing_infections <- function(data, param, i = NULL, custom_function = NULL) {
    .Call(`_measlesoutbreaker_cpp_ll_timing_infections`, data, param, i, custom_function)
}

cpp_ll_timing_sampling <- function(data, param, i = NULL, custom_function = NULL) {
    .Call(`_measlesoutbreaker_cpp_ll_timing_sampling`, data, param, i, custom_function)
}

cpp_ll_space <- function(data, config, param, i = NULL, custom_function = NULL) {
    .Call(`_measlesoutbreaker_cpp_ll_space`, data, config, param, i, custom_function)
}

cpp_ll_age <- function(data, param, i = NULL, custom_function = NULL) {
    .Call(`_measlesoutbreaker_cpp_ll_age`, data, param, i, custom_function)
}

cpp_ll_reporting <- function(data, param, i = NULL, custom_function = NULL) {
    .Call(`_measlesoutbreaker_cpp_ll_reporting`, data, param, i, custom_function)
}

cpp_ll_timing <- function(data, param, i = NULL, custom_functions = NULL) {
    .Call(`_measlesoutbreaker_cpp_ll_timing`, data, param, i, custom_functions)
}

cpp_ll_all <- function(data, config, param, i = NULL, custom_functions = NULL) {
    .Call(`_measlesoutbreaker_cpp_ll_all`, data, config, param, i, custom_functions)
}

cpp_move_a <- function(param, data, config, custom_ll = NULL, custom_prior = NULL) {
    .Call(`_measlesoutbreaker_cpp_move_a`, param, data, config, custom_ll, custom_prior)
}

cpp_move_b <- function(param, data, config, custom_ll = NULL, custom_prior = NULL) {
    .Call(`_measlesoutbreaker_cpp_move_b`, param, data, config, custom_ll, custom_prior)
}

cpp_move_pi <- function(param, data, config, custom_ll = NULL, custom_prior = NULL) {
    .Call(`_measlesoutbreaker_cpp_move_pi`, param, data, config, custom_ll, custom_prior)
}

cpp_move_t_inf <- function(param, data, list_custom_ll = NULL) {
    .Call(`_measlesoutbreaker_cpp_move_t_inf`, param, data, list_custom_ll)
}

cpp_move_alpha <- function(param, data, config, list_custom_ll = NULL) {
    .Call(`_measlesoutbreaker_cpp_move_alpha`, param, data, config, list_custom_ll)
}

cpp_move_ancestors <- function(param, data, config, list_custom_ll = NULL) {
    .Call(`_measlesoutbreaker_cpp_move_ancestors`, param, data, config, list_custom_ll)
}

cpp_move_swap_cases <- function(param, data, config, list_custom_ll = NULL) {
    .Call(`_measlesoutbreaker_cpp_move_swap_cases`, param, data, config, list_custom_ll)
}

cpp_move_kappa <- function(param, data, config, list_custom_ll = NULL) {
    .Call(`_measlesoutbreaker_cpp_move_kappa`, param, data, config, list_custom_ll)
}

cpp_prior_pi <- function(param, config, custom_function = NULL) {
    .Call(`_measlesoutbreaker_cpp_prior_pi`, param, config, custom_function)
}

cpp_prior_a <- function(param, config, custom_function = NULL) {
    .Call(`_measlesoutbreaker_cpp_prior_a`, param, config, custom_function)
}

cpp_prior_b <- function(param, config, custom_function = NULL) {
    .Call(`_measlesoutbreaker_cpp_prior_b`, param, config, custom_function)
}

cpp_prior_all <- function(param, config, custom_functions = NULL) {
    .Call(`_measlesoutbreaker_cpp_prior_all`, param, config, custom_functions)
}

